name: index

on:
  push:

jobs:
  index-core:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Index Action
      uses: ./
      with:
        repository_name: verible-indexing-action
        repository_url: https://github.com/antmicro/verible-indexing-action
        repository_branch: main
        repository_revision: HEAD